apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: default
  name: flink-application-cluster
spec:
  mode: standalone
  image: flink:1.20
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"

    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: "9249"
    metrics.latency.interval: "5000"        # milliseconds, 0 = disabled
    metrics.latency.granularity: "single" # single | operator | subtask

    scheduler-mode: reactive
    # BUG:
    # Enabling checkpointing will lead to source tasks entering `FINISHED` state on rescale events.
    # Therefore we do not specify checkpointing since it is disabled by default.
    # execution.checkpointing.interval: "10s"

    # INFO:
    # The use of savepointing currently appears to break reactive mode.
    # Therefore we removed savepointing and have to set the restart strategy manually
    # since the default is `none`.
    restart-strategy.type: exponential-delay

  serviceAccount: flink
  podTemplate:
    metadata:
      labels:
        # NOTE: Prometheus looks for this `monitoring` label.
        release: monitoring
    spec:
      serviceAccount: flink
      containers:
        - name: flink-main-container
          ports:
            - containerPort: 9249
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: flink-job-dir
              mountPath: /flink-jobs/
      volumes:
        - name: flink-job-dir
          hostPath:
            path: /tmp/flink/jobs
            type: DirectoryOrCreate
  jobManager:
    resource:
      memory: "8g"
      cpu: 4
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///flink-jobs/FlinkJob.jar
    parallelism: 128
    state: running
    args:
      # WARN:
      # Edit this to match the URL of the MongoDB Service.
      # - "--databaseUrl=mongodb://adminuser:password123@mongodb-nodeport.default.svc.cluster.local:32000/"
      - "--experiRunId=TAXI"
