{{- if .Values.additionalTaskManagers.large.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-application-cluster-taskmanager-large
  namespace: default
  labels:
    app: flink-application-cluster
    component: taskmanager
spec:
  selector:
    matchLabels:
      app: flink-application-cluster
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink-application-cluster
        component: taskmanager
        release: monitoring
    spec:
      serviceAccount: flink
      containers:
        - name: taskmanager
          image: flink:1.20
          command: 
            - /docker-entrypoint.sh
            - taskmanager
            - -Dtaskmanager.numberOfTaskSlots=16
            - -Dtaskmanager.memory.process.size=32g
          resources:
            requests:
              memory: "32Gi"
              cpu: "16"
            limits:
              memory: "32Gi"
              cpu: "16"
          env:
            - name: FLINK_CONF_DIR
              value: /opt/flink/conf
          ports:
            - containerPort: 9249
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
            - name: flink-job-dir
              mountPath: /flink-jobs/
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config-flink-application-cluster
        - name: flink-job-dir
          hostPath:
            path: /tmp/flink/jobs
            type: DirectoryOrCreate
{{- end }}
