additionalTaskManagers:
  medium:
    enabled: true
  large:
    enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 64
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
