# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.35.0-standalone-strict/all.json
{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
data:
  password: cGFzc3dvcmQxMjM= #password123
  username: YWRtaW51c2Vy #adminuser
{{- end }}
