{
 "title": "UpStream Metrics",
 "description": "The metrics used by the UpStream scaler to scale the number of task managers of the flink cluster.",
 "time": { "from": "2026-08-14T19:44:01.290Z", "to": "2026-08-14T20:14:57.752Z" },
 "panels": [
  {
   "title": "Average Busy Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_busyTimeMsPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Idle Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_idleTimeMsPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure Time ms/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_backPressuredTimeMsPerSecond)",
     "legendFormat": "backpressure_ms_per_second"
    }
   ]
  },
  {
   "title": "Task Manager replicas",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"flink-application-cluster-taskmanager\"}",
     "legendFormat": "replicas_small"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"flink-application-cluster-taskmanager-medium\"}",
     "legendFormat": "replicas_medium"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"flink-application-cluster-taskmanager-large\"}",
     "legendFormat": "replicas_large"
    }
   ]
  },
  {
   "title": "Kafka incoming Messages/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\", topic=\"senml-source\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\", topic=\"senml-cleaned\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Job Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "avg by(task_name) (flink_taskmanager_job_task_mailboxLatencyMs)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(flink_taskmanager_job_task_mailboxLatencyMs)",
     "legendFormat": "max_latency"
    },
    {
     "expr": "min(flink_taskmanager_job_task_mailboxLatencyMs)",
     "legendFormat": "min_latency"
    }
   ]
  },
  {
   "title": "MongoDB Average Collection Inserts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(mongodb_top_insert_count{collection=\"senml-cleaned\"}[10s])",
     "legendFormat": "insert_rate_senml_cleaned"
    },
    {
     "expr": "rate(mongodb_top_insert_count{collection=\"plots\"}[10s])",
     "legendFormat": "insert_rate_plots"
    }
   ]
  },
  {
   "title": "Taskmanagers CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"flink-application-cluster-taskmanager-.*\", container!=\"\"}[2m])\n  ) by (pod)\n  / ignoring(resource)\n  sum(\n    kube_pod_container_resource_requests{namespace=\"default\", pod=~\"flink-application-cluster-taskmanager-.*\", resource=\"cpu\"}\n  ) by (pod)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taskmanagers RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "(\n  sum(\n    container_memory_working_set_bytes{namespace=\"default\", pod=~\"flink-application-cluster-taskmanager-.*\", container!=\"\"}\n  ) by (pod)\n  / ignoring(resource)\n  sum(\n    kube_pod_container_resource_requests{namespace=\"default\", pod=~\"flink-application-cluster-taskmanager-.*\", resource=\"memory\"}\n  ) by (pod)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}